services:
  - type: web
    name: yt-dlp-microservice
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        generateValue: true
